### PR TITLE
want to merge into master

### PR DESCRIPTION
**Pull request by bkastner**
I will need to have someone else on CM review it.

may also be a confilict that will need resolution.

### CODE REVIEW

**Comment by bkastner** [comment]
@Afish321 Please review so I can merge!  But read the post in slack about protected branches first!

**Comment by Afish321** [comment]
Sorry for looking at this so late - I'll review it quick and get it cleared.

**Comment by Afish321** [comment]
Thanks for finding out about protected branches!

**Review by Afish321 — APPROVED** [review]
Cool, here's to testing!

**Pull request merged**
